/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoWorkosRouteImport } from './routes/demo/workos'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as AuthenticatedPostsRouteImport } from './routes/_authenticated/posts'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiTagsIndexRouteImport } from './routes/api/tags/index'
import { Route as ApiReviewsIndexRouteImport } from './routes/api/reviews/index'
import { Route as ApiReviewPicturesIndexRouteImport } from './routes/api/review-pictures/index'
import { Route as ApiRatingsIndexRouteImport } from './routes/api/ratings/index'
import { Route as ApiLocationsIndexRouteImport } from './routes/api/locations/index'
import { Route as ApiLocationPicturesIndexRouteImport } from './routes/api/location-pictures/index'
import { Route as ApiDishesIndexRouteImport } from './routes/api/dishes/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiTagsIdRouteImport } from './routes/api/tags/$id'
import { Route as ApiReviewsIdRouteImport } from './routes/api/reviews/$id'
import { Route as ApiReviewPicturesIdRouteImport } from './routes/api/review-pictures/$id'
import { Route as ApiRatingsIdRouteImport } from './routes/api/ratings/$id'
import { Route as ApiLocationsIdRouteImport } from './routes/api/locations/$id'
import { Route as ApiLocationPicturesIdRouteImport } from './routes/api/location-pictures/$id'
import { Route as ApiDishesIdRouteImport } from './routes/api/dishes/$id'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkosRoute = DemoWorkosRouteImport.update({
  id: '/demo/workos',
  path: '/demo/workos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostsRoute = AuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTagsIndexRoute = ApiTagsIndexRouteImport.update({
  id: '/api/tags/',
  path: '/api/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsIndexRoute = ApiReviewsIndexRouteImport.update({
  id: '/api/reviews/',
  path: '/api/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewPicturesIndexRoute = ApiReviewPicturesIndexRouteImport.update({
  id: '/api/review-pictures/',
  path: '/api/review-pictures/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingsIndexRoute = ApiRatingsIndexRouteImport.update({
  id: '/api/ratings/',
  path: '/api/ratings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsIndexRoute = ApiLocationsIndexRouteImport.update({
  id: '/api/locations/',
  path: '/api/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationPicturesIndexRoute =
  ApiLocationPicturesIndexRouteImport.update({
    id: '/api/location-pictures/',
    path: '/api/location-pictures/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDishesIndexRoute = ApiDishesIndexRouteImport.update({
  id: '/api/dishes/',
  path: '/api/dishes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsIdRoute = ApiTagsIdRouteImport.update({
  id: '/api/tags/$id',
  path: '/api/tags/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsIdRoute = ApiReviewsIdRouteImport.update({
  id: '/api/reviews/$id',
  path: '/api/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewPicturesIdRoute = ApiReviewPicturesIdRouteImport.update({
  id: '/api/review-pictures/$id',
  path: '/api/review-pictures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingsIdRoute = ApiRatingsIdRouteImport.update({
  id: '/api/ratings/$id',
  path: '/api/ratings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsIdRoute = ApiLocationsIdRouteImport.update({
  id: '/api/locations/$id',
  path: '/api/locations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationPicturesIdRoute = ApiLocationPicturesIdRouteImport.update({
  id: '/api/location-pictures/$id',
  path: '/api/location-pictures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDishesIdRoute = ApiDishesIdRouteImport.update({
  id: '/api/dishes/$id',
  path: '/api/dishes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/dishes/$id': typeof ApiDishesIdRoute
  '/api/location-pictures/$id': typeof ApiLocationPicturesIdRoute
  '/api/locations/$id': typeof ApiLocationsIdRoute
  '/api/ratings/$id': typeof ApiRatingsIdRoute
  '/api/review-pictures/$id': typeof ApiReviewPicturesIdRoute
  '/api/reviews/$id': typeof ApiReviewsIdRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/dishes': typeof ApiDishesIndexRoute
  '/api/location-pictures': typeof ApiLocationPicturesIndexRoute
  '/api/locations': typeof ApiLocationsIndexRoute
  '/api/ratings': typeof ApiRatingsIndexRoute
  '/api/review-pictures': typeof ApiReviewPicturesIndexRoute
  '/api/reviews': typeof ApiReviewsIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/dishes/$id': typeof ApiDishesIdRoute
  '/api/location-pictures/$id': typeof ApiLocationPicturesIdRoute
  '/api/locations/$id': typeof ApiLocationsIdRoute
  '/api/ratings/$id': typeof ApiRatingsIdRoute
  '/api/review-pictures/$id': typeof ApiReviewPicturesIdRoute
  '/api/reviews/$id': typeof ApiReviewsIdRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/dishes': typeof ApiDishesIndexRoute
  '/api/location-pictures': typeof ApiLocationPicturesIndexRoute
  '/api/locations': typeof ApiLocationsIndexRoute
  '/api/ratings': typeof ApiRatingsIndexRoute
  '/api/review-pictures': typeof ApiReviewPicturesIndexRoute
  '/api/reviews': typeof ApiReviewsIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/dishes/$id': typeof ApiDishesIdRoute
  '/api/location-pictures/$id': typeof ApiLocationPicturesIdRoute
  '/api/locations/$id': typeof ApiLocationsIdRoute
  '/api/ratings/$id': typeof ApiRatingsIdRoute
  '/api/review-pictures/$id': typeof ApiReviewPicturesIdRoute
  '/api/reviews/$id': typeof ApiReviewsIdRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/dishes/': typeof ApiDishesIndexRoute
  '/api/location-pictures/': typeof ApiLocationPicturesIndexRoute
  '/api/locations/': typeof ApiLocationsIndexRoute
  '/api/ratings/': typeof ApiRatingsIndexRoute
  '/api/review-pictures/': typeof ApiReviewPicturesIndexRoute
  '/api/reviews/': typeof ApiReviewsIndexRoute
  '/api/tags/': typeof ApiTagsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/account'
    | '/posts'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/api/auth/callback'
    | '/api/dishes/$id'
    | '/api/location-pictures/$id'
    | '/api/locations/$id'
    | '/api/ratings/$id'
    | '/api/review-pictures/$id'
    | '/api/reviews/$id'
    | '/api/tags/$id'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/dishes'
    | '/api/location-pictures'
    | '/api/locations'
    | '/api/ratings'
    | '/api/review-pictures'
    | '/api/reviews'
    | '/api/tags'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/account'
    | '/posts'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/api/auth/callback'
    | '/api/dishes/$id'
    | '/api/location-pictures/$id'
    | '/api/locations/$id'
    | '/api/ratings/$id'
    | '/api/review-pictures/$id'
    | '/api/reviews/$id'
    | '/api/tags/$id'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/dishes'
    | '/api/location-pictures'
    | '/api/locations'
    | '/api/ratings'
    | '/api/review-pictures'
    | '/api/reviews'
    | '/api/tags'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/logout'
    | '/_authenticated/account'
    | '/_authenticated/posts'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/api/auth/callback'
    | '/api/dishes/$id'
    | '/api/location-pictures/$id'
    | '/api/locations/$id'
    | '/api/ratings/$id'
    | '/api/review-pictures/$id'
    | '/api/reviews/$id'
    | '/api/tags/$id'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/dishes/'
    | '/api/location-pictures/'
    | '/api/locations/'
    | '/api/ratings/'
    | '/api/review-pictures/'
    | '/api/reviews/'
    | '/api/tags/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoWorkosRoute: typeof DemoWorkosRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiDishesIdRoute: typeof ApiDishesIdRoute
  ApiLocationPicturesIdRoute: typeof ApiLocationPicturesIdRoute
  ApiLocationsIdRoute: typeof ApiLocationsIdRoute
  ApiRatingsIdRoute: typeof ApiRatingsIdRoute
  ApiReviewPicturesIdRoute: typeof ApiReviewPicturesIdRoute
  ApiReviewsIdRoute: typeof ApiReviewsIdRoute
  ApiTagsIdRoute: typeof ApiTagsIdRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiDishesIndexRoute: typeof ApiDishesIndexRoute
  ApiLocationPicturesIndexRoute: typeof ApiLocationPicturesIndexRoute
  ApiLocationsIndexRoute: typeof ApiLocationsIndexRoute
  ApiRatingsIndexRoute: typeof ApiRatingsIndexRoute
  ApiReviewPicturesIndexRoute: typeof ApiReviewPicturesIndexRoute
  ApiReviewsIndexRoute: typeof ApiReviewsIndexRoute
  ApiTagsIndexRoute: typeof ApiTagsIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workos': {
      id: '/demo/workos'
      path: '/demo/workos'
      fullPath: '/demo/workos'
      preLoaderRoute: typeof DemoWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/tags/': {
      id: '/api/tags/'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/': {
      id: '/api/reviews/'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-pictures/': {
      id: '/api/review-pictures/'
      path: '/api/review-pictures'
      fullPath: '/api/review-pictures'
      preLoaderRoute: typeof ApiReviewPicturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ratings/': {
      id: '/api/ratings/'
      path: '/api/ratings'
      fullPath: '/api/ratings'
      preLoaderRoute: typeof ApiRatingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/': {
      id: '/api/locations/'
      path: '/api/locations'
      fullPath: '/api/locations'
      preLoaderRoute: typeof ApiLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location-pictures/': {
      id: '/api/location-pictures/'
      path: '/api/location-pictures'
      fullPath: '/api/location-pictures'
      preLoaderRoute: typeof ApiLocationPicturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dishes/': {
      id: '/api/dishes/'
      path: '/api/dishes'
      fullPath: '/api/dishes'
      preLoaderRoute: typeof ApiDishesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/$id': {
      id: '/api/tags/$id'
      path: '/api/tags/$id'
      fullPath: '/api/tags/$id'
      preLoaderRoute: typeof ApiTagsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/$id': {
      id: '/api/reviews/$id'
      path: '/api/reviews/$id'
      fullPath: '/api/reviews/$id'
      preLoaderRoute: typeof ApiReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-pictures/$id': {
      id: '/api/review-pictures/$id'
      path: '/api/review-pictures/$id'
      fullPath: '/api/review-pictures/$id'
      preLoaderRoute: typeof ApiReviewPicturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ratings/$id': {
      id: '/api/ratings/$id'
      path: '/api/ratings/$id'
      fullPath: '/api/ratings/$id'
      preLoaderRoute: typeof ApiRatingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/$id': {
      id: '/api/locations/$id'
      path: '/api/locations/$id'
      fullPath: '/api/locations/$id'
      preLoaderRoute: typeof ApiLocationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location-pictures/$id': {
      id: '/api/location-pictures/$id'
      path: '/api/location-pictures/$id'
      fullPath: '/api/location-pictures/$id'
      preLoaderRoute: typeof ApiLocationPicturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dishes/$id': {
      id: '/api/dishes/$id'
      path: '/api/dishes/$id'
      fullPath: '/api/dishes/$id'
      preLoaderRoute: typeof ApiDishesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedPostsRoute: typeof AuthenticatedPostsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedPostsRoute: AuthenticatedPostsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoWorkosRoute: DemoWorkosRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiDishesIdRoute: ApiDishesIdRoute,
  ApiLocationPicturesIdRoute: ApiLocationPicturesIdRoute,
  ApiLocationsIdRoute: ApiLocationsIdRoute,
  ApiRatingsIdRoute: ApiRatingsIdRoute,
  ApiReviewPicturesIdRoute: ApiReviewPicturesIdRoute,
  ApiReviewsIdRoute: ApiReviewsIdRoute,
  ApiTagsIdRoute: ApiTagsIdRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiDishesIndexRoute: ApiDishesIndexRoute,
  ApiLocationPicturesIndexRoute: ApiLocationPicturesIndexRoute,
  ApiLocationsIndexRoute: ApiLocationsIndexRoute,
  ApiRatingsIndexRoute: ApiRatingsIndexRoute,
  ApiReviewPicturesIndexRoute: ApiReviewPicturesIndexRoute,
  ApiReviewsIndexRoute: ApiReviewsIndexRoute,
  ApiTagsIndexRoute: ApiTagsIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
