/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsSlugRouteImport } from './routes/locations/$slug'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiTagsIndexRouteImport } from './routes/api/tags/index'
import { Route as ApiReviewsIndexRouteImport } from './routes/api/reviews/index'
import { Route as ApiReviewPicturesIndexRouteImport } from './routes/api/review-pictures/index'
import { Route as ApiRatingsIndexRouteImport } from './routes/api/ratings/index'
import { Route as ApiLocationsIndexRouteImport } from './routes/api/locations/index'
import { Route as ApiLocationPicturesIndexRouteImport } from './routes/api/location-pictures/index'
import { Route as ApiDishesIndexRouteImport } from './routes/api/dishes/index'
import { Route as AuthenticatedReviewsIndexRouteImport } from './routes/_authenticated/reviews/index'
import { Route as ApiTagsIdRouteImport } from './routes/api/tags/$id'
import { Route as ApiReviewsIdRouteImport } from './routes/api/reviews/$id'
import { Route as ApiReviewPicturesIdRouteImport } from './routes/api/review-pictures/$id'
import { Route as ApiRatingsIdRouteImport } from './routes/api/ratings/$id'
import { Route as ApiLocationsIdRouteImport } from './routes/api/locations/$id'
import { Route as ApiLocationPicturesIdRouteImport } from './routes/api/location-pictures/$id'
import { Route as ApiDishesIdRouteImport } from './routes/api/dishes/$id'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedReviewsNewRouteImport } from './routes/_authenticated/reviews/new'
import { Route as AuthenticatedReviewsIdRouteImport } from './routes/_authenticated/reviews/$id'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTagsIndexRoute = ApiTagsIndexRouteImport.update({
  id: '/api/tags/',
  path: '/api/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsIndexRoute = ApiReviewsIndexRouteImport.update({
  id: '/api/reviews/',
  path: '/api/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewPicturesIndexRoute = ApiReviewPicturesIndexRouteImport.update({
  id: '/api/review-pictures/',
  path: '/api/review-pictures/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingsIndexRoute = ApiRatingsIndexRouteImport.update({
  id: '/api/ratings/',
  path: '/api/ratings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsIndexRoute = ApiLocationsIndexRouteImport.update({
  id: '/api/locations/',
  path: '/api/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationPicturesIndexRoute =
  ApiLocationPicturesIndexRouteImport.update({
    id: '/api/location-pictures/',
    path: '/api/location-pictures/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDishesIndexRoute = ApiDishesIndexRouteImport.update({
  id: '/api/dishes/',
  path: '/api/dishes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewsIndexRoute =
  AuthenticatedReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiTagsIdRoute = ApiTagsIdRouteImport.update({
  id: '/api/tags/$id',
  path: '/api/tags/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsIdRoute = ApiReviewsIdRouteImport.update({
  id: '/api/reviews/$id',
  path: '/api/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewPicturesIdRoute = ApiReviewPicturesIdRouteImport.update({
  id: '/api/review-pictures/$id',
  path: '/api/review-pictures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingsIdRoute = ApiRatingsIdRouteImport.update({
  id: '/api/ratings/$id',
  path: '/api/ratings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsIdRoute = ApiLocationsIdRouteImport.update({
  id: '/api/locations/$id',
  path: '/api/locations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationPicturesIdRoute = ApiLocationPicturesIdRouteImport.update({
  id: '/api/location-pictures/$id',
  path: '/api/location-pictures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDishesIdRoute = ApiDishesIdRouteImport.update({
  id: '/api/dishes/$id',
  path: '/api/dishes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewsNewRoute = AuthenticatedReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewsIdRoute = AuthenticatedReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/reviews/$id': typeof AuthenticatedReviewsIdRoute
  '/reviews/new': typeof AuthenticatedReviewsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/dishes/$id': typeof ApiDishesIdRoute
  '/api/location-pictures/$id': typeof ApiLocationPicturesIdRoute
  '/api/locations/$id': typeof ApiLocationsIdRoute
  '/api/ratings/$id': typeof ApiRatingsIdRoute
  '/api/review-pictures/$id': typeof ApiReviewPicturesIdRoute
  '/api/reviews/$id': typeof ApiReviewsIdRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/reviews': typeof AuthenticatedReviewsIndexRoute
  '/api/dishes': typeof ApiDishesIndexRoute
  '/api/location-pictures': typeof ApiLocationPicturesIndexRoute
  '/api/locations': typeof ApiLocationsIndexRoute
  '/api/ratings': typeof ApiRatingsIndexRoute
  '/api/review-pictures': typeof ApiReviewPicturesIndexRoute
  '/api/reviews': typeof ApiReviewsIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/reviews/$id': typeof AuthenticatedReviewsIdRoute
  '/reviews/new': typeof AuthenticatedReviewsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/dishes/$id': typeof ApiDishesIdRoute
  '/api/location-pictures/$id': typeof ApiLocationPicturesIdRoute
  '/api/locations/$id': typeof ApiLocationsIdRoute
  '/api/ratings/$id': typeof ApiRatingsIdRoute
  '/api/review-pictures/$id': typeof ApiReviewPicturesIdRoute
  '/api/reviews/$id': typeof ApiReviewsIdRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/reviews': typeof AuthenticatedReviewsIndexRoute
  '/api/dishes': typeof ApiDishesIndexRoute
  '/api/location-pictures': typeof ApiLocationPicturesIndexRoute
  '/api/locations': typeof ApiLocationsIndexRoute
  '/api/ratings': typeof ApiRatingsIndexRoute
  '/api/review-pictures': typeof ApiReviewPicturesIndexRoute
  '/api/reviews': typeof ApiReviewsIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/_authenticated/reviews/$id': typeof AuthenticatedReviewsIdRoute
  '/_authenticated/reviews/new': typeof AuthenticatedReviewsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/dishes/$id': typeof ApiDishesIdRoute
  '/api/location-pictures/$id': typeof ApiLocationPicturesIdRoute
  '/api/locations/$id': typeof ApiLocationsIdRoute
  '/api/ratings/$id': typeof ApiRatingsIdRoute
  '/api/review-pictures/$id': typeof ApiReviewPicturesIdRoute
  '/api/reviews/$id': typeof ApiReviewsIdRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/_authenticated/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/api/dishes/': typeof ApiDishesIndexRoute
  '/api/location-pictures/': typeof ApiLocationPicturesIndexRoute
  '/api/locations/': typeof ApiLocationsIndexRoute
  '/api/ratings/': typeof ApiRatingsIndexRoute
  '/api/review-pictures/': typeof ApiReviewPicturesIndexRoute
  '/api/reviews/': typeof ApiReviewsIndexRoute
  '/api/tags/': typeof ApiTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/account'
    | '/locations/$slug'
    | '/reviews/$id'
    | '/reviews/new'
    | '/api/auth/callback'
    | '/api/dishes/$id'
    | '/api/location-pictures/$id'
    | '/api/locations/$id'
    | '/api/ratings/$id'
    | '/api/review-pictures/$id'
    | '/api/reviews/$id'
    | '/api/tags/$id'
    | '/reviews'
    | '/api/dishes'
    | '/api/location-pictures'
    | '/api/locations'
    | '/api/ratings'
    | '/api/review-pictures'
    | '/api/reviews'
    | '/api/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/account'
    | '/locations/$slug'
    | '/reviews/$id'
    | '/reviews/new'
    | '/api/auth/callback'
    | '/api/dishes/$id'
    | '/api/location-pictures/$id'
    | '/api/locations/$id'
    | '/api/ratings/$id'
    | '/api/review-pictures/$id'
    | '/api/reviews/$id'
    | '/api/tags/$id'
    | '/reviews'
    | '/api/dishes'
    | '/api/location-pictures'
    | '/api/locations'
    | '/api/ratings'
    | '/api/review-pictures'
    | '/api/reviews'
    | '/api/tags'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/logout'
    | '/_authenticated/account'
    | '/locations/$slug'
    | '/_authenticated/reviews/$id'
    | '/_authenticated/reviews/new'
    | '/api/auth/callback'
    | '/api/dishes/$id'
    | '/api/location-pictures/$id'
    | '/api/locations/$id'
    | '/api/ratings/$id'
    | '/api/review-pictures/$id'
    | '/api/reviews/$id'
    | '/api/tags/$id'
    | '/_authenticated/reviews/'
    | '/api/dishes/'
    | '/api/location-pictures/'
    | '/api/locations/'
    | '/api/ratings/'
    | '/api/review-pictures/'
    | '/api/reviews/'
    | '/api/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiDishesIdRoute: typeof ApiDishesIdRoute
  ApiLocationPicturesIdRoute: typeof ApiLocationPicturesIdRoute
  ApiLocationsIdRoute: typeof ApiLocationsIdRoute
  ApiRatingsIdRoute: typeof ApiRatingsIdRoute
  ApiReviewPicturesIdRoute: typeof ApiReviewPicturesIdRoute
  ApiReviewsIdRoute: typeof ApiReviewsIdRoute
  ApiTagsIdRoute: typeof ApiTagsIdRoute
  ApiDishesIndexRoute: typeof ApiDishesIndexRoute
  ApiLocationPicturesIndexRoute: typeof ApiLocationPicturesIndexRoute
  ApiLocationsIndexRoute: typeof ApiLocationsIndexRoute
  ApiRatingsIndexRoute: typeof ApiRatingsIndexRoute
  ApiReviewPicturesIndexRoute: typeof ApiReviewPicturesIndexRoute
  ApiReviewsIndexRoute: typeof ApiReviewsIndexRoute
  ApiTagsIndexRoute: typeof ApiTagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/tags/': {
      id: '/api/tags/'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/': {
      id: '/api/reviews/'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-pictures/': {
      id: '/api/review-pictures/'
      path: '/api/review-pictures'
      fullPath: '/api/review-pictures'
      preLoaderRoute: typeof ApiReviewPicturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ratings/': {
      id: '/api/ratings/'
      path: '/api/ratings'
      fullPath: '/api/ratings'
      preLoaderRoute: typeof ApiRatingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/': {
      id: '/api/locations/'
      path: '/api/locations'
      fullPath: '/api/locations'
      preLoaderRoute: typeof ApiLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location-pictures/': {
      id: '/api/location-pictures/'
      path: '/api/location-pictures'
      fullPath: '/api/location-pictures'
      preLoaderRoute: typeof ApiLocationPicturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dishes/': {
      id: '/api/dishes/'
      path: '/api/dishes'
      fullPath: '/api/dishes'
      preLoaderRoute: typeof ApiDishesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reviews/': {
      id: '/_authenticated/reviews/'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/tags/$id': {
      id: '/api/tags/$id'
      path: '/api/tags/$id'
      fullPath: '/api/tags/$id'
      preLoaderRoute: typeof ApiTagsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/$id': {
      id: '/api/reviews/$id'
      path: '/api/reviews/$id'
      fullPath: '/api/reviews/$id'
      preLoaderRoute: typeof ApiReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-pictures/$id': {
      id: '/api/review-pictures/$id'
      path: '/api/review-pictures/$id'
      fullPath: '/api/review-pictures/$id'
      preLoaderRoute: typeof ApiReviewPicturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ratings/$id': {
      id: '/api/ratings/$id'
      path: '/api/ratings/$id'
      fullPath: '/api/ratings/$id'
      preLoaderRoute: typeof ApiRatingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/$id': {
      id: '/api/locations/$id'
      path: '/api/locations/$id'
      fullPath: '/api/locations/$id'
      preLoaderRoute: typeof ApiLocationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location-pictures/$id': {
      id: '/api/location-pictures/$id'
      path: '/api/location-pictures/$id'
      fullPath: '/api/location-pictures/$id'
      preLoaderRoute: typeof ApiLocationPicturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dishes/$id': {
      id: '/api/dishes/$id'
      path: '/api/dishes/$id'
      fullPath: '/api/dishes/$id'
      preLoaderRoute: typeof ApiDishesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reviews/new': {
      id: '/_authenticated/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof AuthenticatedReviewsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews/$id': {
      id: '/_authenticated/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof AuthenticatedReviewsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedReviewsIdRoute: typeof AuthenticatedReviewsIdRoute
  AuthenticatedReviewsNewRoute: typeof AuthenticatedReviewsNewRoute
  AuthenticatedReviewsIndexRoute: typeof AuthenticatedReviewsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedReviewsIdRoute: AuthenticatedReviewsIdRoute,
  AuthenticatedReviewsNewRoute: AuthenticatedReviewsNewRoute,
  AuthenticatedReviewsIndexRoute: AuthenticatedReviewsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiDishesIdRoute: ApiDishesIdRoute,
  ApiLocationPicturesIdRoute: ApiLocationPicturesIdRoute,
  ApiLocationsIdRoute: ApiLocationsIdRoute,
  ApiRatingsIdRoute: ApiRatingsIdRoute,
  ApiReviewPicturesIdRoute: ApiReviewPicturesIdRoute,
  ApiReviewsIdRoute: ApiReviewsIdRoute,
  ApiTagsIdRoute: ApiTagsIdRoute,
  ApiDishesIndexRoute: ApiDishesIndexRoute,
  ApiLocationPicturesIndexRoute: ApiLocationPicturesIndexRoute,
  ApiLocationsIndexRoute: ApiLocationsIndexRoute,
  ApiRatingsIndexRoute: ApiRatingsIndexRoute,
  ApiReviewPicturesIndexRoute: ApiReviewPicturesIndexRoute,
  ApiReviewsIndexRoute: ApiReviewsIndexRoute,
  ApiTagsIndexRoute: ApiTagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
